<?php

return array(

	'use_typekit' => TRUE,
	'use_analyrics' => TRUE,
	'use_googleapis' => TRUE,
	'use_googlefonts' => TRUE,
	'use_css_local' => FALSE,
	'use_scripts_local' => FALSE,
	
	'default_page_title' => 'Эй Джен',
	'template' => 'site',
    'welcome_page_tpl' => 'templates.site.index', #'guests.welcome',

	'manifest' => storage_path('meta'),

	'debug' => TRUE,
	'url' => '#',
	'timezone' => 'UTC',

    'locales' => array(
        'ru' => 'Русский',
        #'en' => 'English',
    ),
	'locale' => 'ru',

	'key' => 'TSHZVixcD1cLGLSTObouk6Tmo3ChmyxD',
	'providers' => array(
		'Illuminate\Foundation\Providers\ArtisanServiceProvider',
		'Illuminate\Auth\AuthServiceProvider',
		'Illuminate\Cache\CacheServiceProvider',
		'Illuminate\Session\CommandsServiceProvider',
		'Illuminate\Foundation\Providers\ConsoleSupportServiceProvider',
		'Illuminate\Routing\ControllerServiceProvider',
		'Illuminate\Cookie\CookieServiceProvider',
		'Illuminate\Database\DatabaseServiceProvider',
		'Illuminate\Encryption\EncryptionServiceProvider',
		'Illuminate\Filesystem\FilesystemServiceProvider',
		'Illuminate\Hashing\HashServiceProvider',
		'Illuminate\Html\HtmlServiceProvider',
		'Illuminate\Log\LogServiceProvider',
		'Illuminate\Mail\MailServiceProvider',
		'Illuminate\Database\MigrationServiceProvider',
		'Illuminate\Pagination\PaginationServiceProvider',
		'Illuminate\Queue\QueueServiceProvider',
		'Illuminate\Redis\RedisServiceProvider',
		'Illuminate\Remote\RemoteServiceProvider',
		'Illuminate\Auth\Reminders\ReminderServiceProvider',
		'Illuminate\Database\SeedServiceProvider',
		'Illuminate\Session\SessionServiceProvider',
		'Illuminate\Translation\TranslationServiceProvider',
		'Illuminate\Validation\ValidationServiceProvider',
		'Illuminate\View\ViewServiceProvider',
		'Illuminate\Workbench\WorkbenchServiceProvider',
		'Way\Generators\GeneratorsServiceProvider',
		'Intervention\Image\ImageServiceProvider',
        'Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider',
        'Flynsarmy\DbBladeCompiler\DbBladeCompilerServiceProvider',
        'sngrl\StringBladeCompiler\StringBladeCompilerServiceProvider',
        'Sngrl\Routing\CustomUrlServiceProvider',
        'Sngrl\Routing\CustomRoutingServiceProvider',
    ),
	'aliases' => array(
		'App'             => 'Illuminate\Support\Facades\App',
		'Artisan'         => 'Illuminate\Support\Facades\Artisan',
		'Auth'            => 'Illuminate\Support\Facades\Auth',
		'Blade'           => 'Illuminate\Support\Facades\Blade',
		'Cache'           => 'Illuminate\Support\Facades\Cache',
		'Carbon'          => 'Carbon\Carbon',
		'ClassLoader'     => 'Illuminate\Support\ClassLoader',
		'Config'          => 'Illuminate\Support\Facades\Config',
		'Controller'      => 'Illuminate\Routing\Controller',
		'Cookie'          => 'Illuminate\Support\Facades\Cookie',
		'Crypt'           => 'Illuminate\Support\Facades\Crypt',
		'DB'              => 'Illuminate\Support\Facades\DB',
        'DbView'          => 'Flynsarmy\DbBladeCompiler\Facades\DbView',
		'Eloquent'        => 'Illuminate\Database\Eloquent\Model',
		'Event'           => 'Illuminate\Support\Facades\Event',
		'File'            => 'Illuminate\Support\Facades\File',
		'Form'            => 'Illuminate\Support\Facades\Form',
		'Hash'            => 'Illuminate\Support\Facades\Hash',

		#'HTML'            => 'Illuminate\Support\Facades\HTML',
		'HTML'            => 'Egg\Facades\HTML',

        'Input'           => 'Illuminate\Support\Facades\Input',
		'Lang'            => 'Illuminate\Support\Facades\Lang',
		'Log'             => 'Illuminate\Support\Facades\Log',
		'Mail'            => 'Illuminate\Support\Facades\Mail',
		'Paginator'       => 'Illuminate\Support\Facades\Paginator',
		'Password'        => 'Illuminate\Support\Facades\Password',
		'Queue'           => 'Illuminate\Support\Facades\Queue',
		'Redirect'        => 'Illuminate\Support\Facades\Redirect',
		'Redis'           => 'Illuminate\Support\Facades\Redis',
		'Request'         => 'Illuminate\Support\Facades\Request',
		'Response'        => 'Illuminate\Support\Facades\Response',

		#'Route'           => 'Illuminate\Support\Facades\Route',
		'Route'           => 'Sngrl\Support\Facades\CustomRoute',

		'Schema'          => 'Illuminate\Support\Facades\Schema',
		'Seeder'          => 'Illuminate\Database\Seeder',
		'Session'         => 'Illuminate\Support\Facades\Session',
		'SSH'             => 'Illuminate\Support\Facades\SSH',
		'Str'             => 'Illuminate\Support\Str',

        #'URL'             => 'Illuminate\Support\Facades\URL',
        'URL'             => 'Sngrl\Support\Facades\CustomURL',

		'Validator'       => 'Illuminate\Support\Facades\Validator',
		'View'            => 'Illuminate\Support\Facades\View',
		'ImageManipulation' => 'Intervention\Image\Facades\Image',
        'Collection'      => 'Illuminate\Database\Eloquent\Collection',
	),
);